name: SelfHostedRunnerDemo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  self-hosted-job:    
    runs-on: [ self-hosted, x64, linux ]
    steps:      
      - uses: actions/checkout@v2.5.0
      
      - name: Run a one-line script
        run: echo Hello, world!
